-- ========================
-- 1️⃣ Bảng tài khoản
-- ========================
CREATE TABLE tai_khoan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_dang_nhap VARCHAR(50) UNIQUE,
    mat_khau VARCHAR(255),
    vai_tro VARCHAR(50),
    ho_ten VARCHAR(255),
    email VARCHAR(255),
    ngay_tao TIMESTAMP,
    trang_thai VARCHAR(20)
);

-- ========================
-- 2️⃣ Bảng hộ khẩu
-- ========================
CREATE TABLE ho_khau (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_ho_khau VARCHAR(50) UNIQUE,
    ten_chu_ho VARCHAR(255),
    dia_chi VARCHAR(255),
    ngay_tao DATE,
    noi_dung_thay_doi_chu_ho VARCHAR(500),
    ngay_thay_doi_chu_ho DATE,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_hokhau_created_by FOREIGN KEY (created_by) REFERENCES tai_khoan(id),
    CONSTRAINT fk_hokhau_updated_by FOREIGN KEY (updated_by) REFERENCES tai_khoan(id)
);

-- ========================
-- 3️⃣ Bảng nhân khẩu
-- ========================
CREATE TABLE nhan_khau (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ho_ten VARCHAR(255),
    ngay_sinh DATE,
    gioi_tinh VARCHAR(20),
    dan_toc VARCHAR(50),
    quoc_tich VARCHAR(50),
    nghe_nghiep VARCHAR(255),
    cmnd_cccd VARCHAR(20),
    ngay_cap DATE,
    noi_cap VARCHAR(255),
    quan_he_chu_ho VARCHAR(50),
    ngay_chuyen_di DATE,
    noi_chuyen_di VARCHAR(255),
    ghi_chu VARCHAR(255),
    tam_vang_tu DATE,
    tam_vang_den DATE,
    tam_tru_tu DATE,
    tam_tru_den DATE,
    ho_khau_id BIGINT,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_nhankhau_hokhau FOREIGN KEY (ho_khau_id) REFERENCES ho_khau(id),
    CONSTRAINT fk_nhankhau_created_by FOREIGN KEY (created_by) REFERENCES tai_khoan(id),
    CONSTRAINT fk_nhankhau_updated_by FOREIGN KEY (updated_by) REFERENCES tai_khoan(id)
);

-- ========================
-- 4️⃣ Bảng biến động
-- ========================
CREATE TABLE bien_dong (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loai VARCHAR(100),
    noi_dung VARCHAR(1000),
    thoi_gian TIMESTAMP,
    ho_khau_id BIGINT,
    nhan_khau_id BIGINT,
    created_by BIGINT,
    created_at TIMESTAMP,
    CONSTRAINT fk_biendong_hokhau FOREIGN KEY (ho_khau_id) REFERENCES ho_khau(id),
    CONSTRAINT fk_biendong_nhankhau FOREIGN KEY (nhan_khau_id) REFERENCES nhan_khau(id),
    CONSTRAINT fk_biendong_created_by FOREIGN KEY (created_by) REFERENCES tai_khoan(id)
);

-- ========================
-- 5️⃣ Bảng đợt thu phí
-- ========================
CREATE TABLE dot_thu_phi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_dot VARCHAR(255),
    loai VARCHAR(50),
    ngay_bat_dau DATE,
    ngay_ket_thuc DATE,
    dinh_muc DECIMAL(15,2),
    created_by BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_dotthuphi_created_by FOREIGN KEY (created_by) REFERENCES tai_khoan(id)
);

-- ========================
-- 6️⃣ Bảng thu phí hộ khẩu
-- ========================
CREATE TABLE thu_phi_ho_khau (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ho_khau_id BIGINT,
    dot_thu_phi_id BIGINT,
    so_tien_da_thu DECIMAL(15,2),
    ngay_thu DATE,
    months VARCHAR(50),
    ghi_chu VARCHAR(500),
    collected_by BIGINT,
    created_at TIMESTAMP,
    CONSTRAINT fk_thuphi_hokhau FOREIGN KEY (ho_khau_id) REFERENCES ho_khau(id),
    CONSTRAINT fk_thuphi_dotthuphi FOREIGN KEY (dot_thu_phi_id) REFERENCES dot_thu_phi(id),
    CONSTRAINT fk_thuphi_collected_by FOREIGN KEY (collected_by) REFERENCES tai_khoan(id)
);



