-- ========================
-- 1️⃣ Bảng tài khoản
-- ========================
CREATE TABLE tai_khoan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_dang_nhap VARCHAR(50) UNIQUE,
    mat_khau VARCHAR(255),
    vai_tro VARCHAR(50),
    ho_ten VARCHAR(255),
    email VARCHAR(255),
    ngay_tao TIMESTAMP
);

-- ========================
-- 2️⃣ Bảng hộ khẩu
-- ========================
CREATE TABLE ho_khau (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_ho_khau VARCHAR(50) UNIQUE,
    ten_chu_ho VARCHAR(255),
    dia_chi VARCHAR(255),
    ngay_tao DATE
);

-- ========================
-- 3️⃣ Bảng nhân khẩu
-- ========================
CREATE TABLE nhan_khau (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ho_ten VARCHAR(255),
    ngay_sinh DATE,
    gioi_tinh VARCHAR(20),
    dan_toc VARCHAR(50),
    quoc_tich VARCHAR(50),
    que_quan VARCHAR(255),
    nghe_nghiep VARCHAR(255),
    cmnd_cccd VARCHAR(20),
    ngay_cap DATE,
    noi_cap VARCHAR(255),
    quan_he_chu_ho VARCHAR(50),
    ghi_chu VARCHAR(255),
    tam_vang_tu DATE,
    tam_vang_den DATE,
    tam_tru_tu DATE,
    tam_tru_den DATE,
    ho_khau_id BIGINT,
    trang_thai VARCHAR(20) DEFAULT 'THUONG_TRU',
    CONSTRAINT fk_nhankhau_hokhau FOREIGN KEY (ho_khau_id) REFERENCES ho_khau(id) ON DELETE CASCADE
);

-- ========================
-- 4️⃣ Bảng biến động
-- ========================
CREATE TABLE bien_dong (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loai VARCHAR(100),
    noi_dung VARCHAR(1000),
    thoi_gian TIMESTAMP,
    ho_khau_id BIGINT,
    nhan_khau_id BIGINT,
    CONSTRAINT fk_biendong_hokhau FOREIGN KEY (ho_khau_id) REFERENCES ho_khau(id) ON DELETE CASCADE ,
    CONSTRAINT fk_biendong_nhankhau FOREIGN KEY (nhan_khau_id) REFERENCES nhan_khau(id) ON DELETE CASCADE
);

-- ========================
-- 5️⃣ Bảng đợt thu phí
-- ========================
CREATE TABLE dot_thu_phi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_dot VARCHAR(255),
    loai VARCHAR(20) CHECK (loai IN ('BAT_BUOC', 'TU_NGUYEN')),
    ngay_bat_dau DATE,
    ngay_ket_thuc DATE,
    dinh_muc DECIMAL(15,2)
);

COMMENT ON COLUMN dot_thu_phi.loai IS 'Loại phí: BAT_BUOC (bắt buộc) hoặc TU_NGUYEN (tự nguyện)';

-- ========================
-- 6️⃣ Bảng thu phí hộ khẩu
-- ========================
CREATE TABLE thu_phi_ho_khau (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ho_khau_id BIGINT,
    dot_thu_phi_id BIGINT,
    so_nguoi INT,
    tong_phi DECIMAL(15,2),
    trang_thai VARCHAR(20) CHECK (trang_thai IN ('CHUA_NOP', 'DA_NOP')),
    ngay_thu DATE,
    ghi_chu VARCHAR(500),
    CONSTRAINT fk_thuphi_hokhau FOREIGN KEY (ho_khau_id) REFERENCES ho_khau(id) ON DELETE CASCADE,
    CONSTRAINT fk_thuphi_dotthuphi FOREIGN KEY (dot_thu_phi_id) REFERENCES dot_thu_phi(id)
);

COMMENT ON COLUMN thu_phi_ho_khau.so_nguoi IS 'Số người trong hộ được tính tại thời điểm ghi nhận';
COMMENT ON COLUMN thu_phi_ho_khau.tong_phi IS 'Tổng phí thực tế. Phí BAT_BUOC = dinh_muc * so_nguoi; phí TU_NGUYEN do hộ tự khai báo';
COMMENT ON COLUMN thu_phi_ho_khau.trang_thai IS 'Trạng thái: CHUA_NOP (chưa nộp đủ), DA_NOP (đã nộp đủ)';




